apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-api
  namespace: aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-api
  template:
    metadata:
      labels:
        app: incident-api
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: incident-api
          image: aiops-incident-assistant-app:security
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8001
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql+psycopg://aiops:$(POSTGRES_PASSWORD)@postgres:5432/aiops"
            - name: PROMETHEUS_URL
              value: "http://prometheus:9090"
            - name: LOKI_URL
              value: "http://loki:3100"
          command:
            - uvicorn
            - app.incident_api.main:app
            - --host
            - 0.0.0.0
            - --port
            - "8001"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: incident-api
  namespace: aiops
spec:
  selector:
    app: incident-api
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
