"""Add RCA table

Revision ID: f8481146c1ce
Revises: dab358073779
Create Date: 2026-09-09 11:58:14.280971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8481146c1ce'
down_revision: Union[str, Sequence[str], None] = 'dab358073779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('verification_steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rcas')
    # ### end Alembic commands ###
