apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: aiops
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      enableServiceLinks: false
      restartPolicy: Never
      containers:
        - name: db-migration
          image: aiops-incident-assistant-app:security
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql+psycopg://aiops:$(POSTGRES_PASSWORD)@postgres:5432/aiops"
          command:
            - alembic
            - upgrade
            - head
